### ISSUE TITLE
Erro ao editar página - Reload time out

### ISSUE THREAD

**Issue by paulopereiralr** [IMarcelF/IGRP-Framework#1759]
![image](https://github.com/NOSiCode-CV/IGRP-Framework/assets/140891231/51c7a5cf-4ee7-4e86-bcfd-47021f899e87)
![image](https://github.com/NOSiCode-CV/IGRP-Framework/assets/140891231/4efda32f-1b7b-4dfd-984f-6a4c07037b64)

**Comment by NOSiopen** [comment]
Funcional
