### ISSUE TITLE
Two or more buttons in one page with the same tag shares the same action created in controller page.

### ISSUE THREAD

**Issue by williamfonseca13** [IMarcelF/IGRP-Framework#1767]
### Resumo

Two or more buttons in one page with the same tag generates share the same action created in controller page.

### Passos para reproduzir

Add at leat two buttons with the same tag.

### Qual é o atual comportamento * bug *?

Only one action is created because the action name is being validate using the button tag name.

### Qual é o comportamento * correto * esperado?

A message, alert, warning, etc, should be  introduced to the user editing the page to inform that a button with the current tag name already exists.

/ label ~ bug

**Comment by NOSiopen** [comment]
Corrigido 
<img width="279" alt="image" src="https://github.com/NOSiCode-CV/IGRP-Framework/assets/28312206/611d4099-e2eb-440f-bd34-da1afcf766d9">
