### ISSUE TITLE
Falha ao tentar configurar componente

### ISSUE THREAD

**Issue by Herikson** [IMarcelF/IGRP-Framework#1798]
Falha ao tentar configurar componente

Não abre a janela para editar settings

![2023-11-09 (3)](https://github.com/NOSiCode-CV/IGRP-Framework/assets/12613330/2252f473-99d2-4798-b808-c7a7ac53a36d)

**Comment by NOSiopen** [comment]
Corrigido para novas paginas! 
Criar nova pagina de novo na versão v.231110 apenas no sonartype.nosi.cv mas amanha irá para o mvn central
