### ISSUE TITLE
Bugs no componente “Date” quanto ao formato e opções de data na versão 2.4

### ISSUE THREAD

**Issue by marcelomonteironosi** [IMarcelF/IGRP-Framework#1809]
Para um componente “Date”, o padrão fica como dd-MMM-yyyy (ex.: 01-Jan-2024), mas há uma validação que não permite este formato:

![image](https://github.com/NOSiCode-CV/IGRP-Framework/assets/156930325/683cc321-8f0b-41be-91c9-10b6d2b855f5)

Para contornar este issue, converti o componente para o tipo “Text”, e no valor de exemplo (“Lorem ipsum…”) escrevi uma data aleatória no formato dd-MM-yyyy (ex.: 05-07-2024) e reconverti novamente no tipo “Date” e o formato ficou como o pretendido, e o problema de validação foi contornado. De seguida, num cenário de teste, tentei selecionar uma data, e de seguida o componente solicita adicionar uma hora, sendo que esta opção está desativada no gerador:

![image](https://github.com/NOSiCode-CV/IGRP-Framework/assets/156930325/2217590f-077b-40d5-ab07-c9f970723bf5)

![image](https://github.com/NOSiCode-CV/IGRP-Framework/assets/156930325/51339365-2ba7-4968-9aed-956b6fb45e72)
 
Versão no POM.xml:

<dependency>
			<groupId>cv.igrp</groupId>
			<artifactId>igrp-core-war</artifactId>
			<version>[2.0.0,3.0.0)</version>
			<type>war</type>
</dependency>
<dependency>
			<groupId>cv.igrp</groupId>
			<artifactId>igrp-core</artifactId>
			<version>[2.0.0,3.0.0)</version>
			<type>jar</type>
</dependency>

**Comment by NOSiopen** [comment]
Did not find anymore the issue. Please check again and if occurs, report
