### ISSUE TITLE
[SECURITY VULNERABILITY] In your codebase is a reference of the cdn com polyfill com io service

### ISSUE THREAD

**Issue by PriNova** [IMarcelF/IGRP-Framework#1817]
https://github.com/NOSiCode-CV/IGRP-Framework/blob/07bd8b160bebd5c230c7dae00a887fd789b68d18/IGRP/src/main/webapp/images/IGRP/IGRP2.4/libs/choices.js/README.md?plain=1#L1073

This file is using the cdn.polyfill.io service which is known for injecting malicious code. Please check if there are other references in your codebase.

Please use the cloudflare polyfill service

https://x.com/WeldPond/status/1805973940642119900

**Comment by NOSiopen** [comment]
Thank You will review this

**Comment by NOSiopen** [comment]
It has been resolved. Thanks for the support @PriNova
