### ISSUE TITLE
Campo select multiple fica com valor null mesmo depois de escolhido para o tipo Long

### ISSUE THREAD

**Issue by marcelomonteironosi** [IMarcelF/IGRP-Framework#1828]
### Resumo

Em uma página com um campo do tipo select, com a opção "Multiple" selecionada e java type "Long":

Ao tentar obter os valores escolhidos através do seu getter no objeto "model", o valor retornado é null mesmo com os valores indicados na interface.

### Passos para reproduzir

- Crie um campo do tipo select e selecione "Multiple" e indique o java type como Long
- Defina as opções definindo um HashMap com keys em valor Long e value um texto qualquer (ex.: {1: "Option 1", 2: "Option 2"}
- Tente obter o valor deste após uma ação de submit com um botão neste formulário através do getter no model (model.getField( ) por exemplo)

### Qual é o atual comportamento * bug *?

O valor desde campo no objeto model é null

### Qual é o comportamento * correto * esperado?

O valor devia ser um array dos IDs em Long definido como key através do HashMap<Long, String> quando foi feito o set no view.

### Outras informações
Versão do IGRP: 2.0.0.240807 (IGRP 2.3 - Legacy)

**Comment by NOSiopen** [comment]
@marcelomonteironosi verificar se já está resolvido!
